---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: backend
    init: |
      cd ./server
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    command: cd /workspace/chief-plat/server && sh run.sh
    openMode: split-right
  
  - name: backend
    init: |
      cd ./web
      npm install
    command: cd /workspace/chief-plat/web && npm run dev
    openMode: split-right


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: ignore
  - port: 3000
    onOpen: open-browser


github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod


vscode:
  extensions:
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - ms-python.python
    - bradlc.vscode-tailwindcss
    - rangav.vscode-thunder-client
    - johnsoncodehk.vscode-typescript-vue-plugin
    - johnsoncodehk.volar
